### PR TITLE
Add compatibility with gatesgarth and hardknott

### PR DESCRIPTION
**Pull request by kk6ho**

### CODE REVIEW

**Comment by kk6ho** [comment]
@ssfivy I was wondering if you can merge my PR I submitted last month since gatesgarth is the current Yocto stable release  (3.2) and hardknott (Yocto 3.3)  will be the next stable release in a few weeks?

I see in the Readme.md that there is a TODO to setup branches for each release.  I agree that that is a good thing to do.
I think that separate release branches should  be added rather than having a single master branch with all releases listed in the LAYERSERIES_COMPAT variable.  That follows the pattern of other meta layers. 

Also if there are other release branches, I think the meta-noto layer will become more popular since some users may now resist using layers which are only have a master branch, rather than ones that are keyed to a Yocto release.

If release branches are created, then the recipe pages at https://layers.openembedded.org will show all the released versions in the Other branches section .  For example, the recipe page for noto-sans-jp, http://layers.openembedded.org/layerindex/recipe/119204/,  would show branches other than master. Also release branches could have different versions of the recipe if desired, and deprecated or EOL branches do not need to be updated or tested each time master changes.

If you like, I could submit a set of PRs to implement this (a PR for each branch created would be needed).  Let me know.

Thanks,
Geoff

**Comment by ssfivy** [comment]
Hi,
Thanks for following up. Just merged your PR. (I tend to get notified by emails instead of being logged in github all the time, so if I don't respond you can send follow-up emails.)

I like your suggestions for having separate branches. If you want to create PRs to do so I will happily merge them in.

Ideally I would like to have automated CI to check if things builds just fine, but Yocto being Yocto it wants to recompile the cross-toolchain all the time which makes it infeasible to use any CI providers' free tiers. There might be a way around with precopiled docker containers / artifacts but that brings in another level of complexity that I'm not sure I want - considering all these recipes basically are just "put file on sysroot".

**Comment by kk6ho** [comment]
Hi Irving,

Thanks for merging my PR.  I'll try to create the PRs for the multiple
Yocto release branches this weekend.

I think the changes to meta-noto should not trigger a rebuild of everything
if you are using sstate-cache.  I know how frustrating that can be
however.  I think I've seen changes to fonts trigger a  rebuild of systemd,
which triggers a rebuild of qt5-base, etc. which is painful.  I wouldn't
expect it to be triggering rebuilds of the toolchain. You might be seeing
more churn of toolchain builds if you are building off the Yocto master
branch meta-layers  rather than the release branches, which are more static.

For my development work, I normally build locally on a laptop without
CI/CD. But my company does daily and on-demand CI/CD Yocto builds.
Previously we used on-premises servers and VMs, but now are doing Jenkins
builds in AWS cloud instances and use S3 to persistently store state-cache
between builds. This is key for quick, incremental builds.

**Comment by kk6ho** [comment]
Hi Irving,

I have the branches ready to submit to your meta-noto repo on GitHub.  I'm
not sure how to do a PR with GitHub's workflow to a new branch if that
branch does not already exist in the upstream repo.  Can you create these
new branches on your meta-noto and send me an email when done? Then I can
send my PRs to each branch.  The list of branches to be branched from the
current master branch HEAD are:    thud  warrior zeus dunfell gatesgarth
hardknott.

Thanks

**Comment by ssfivy** [comment]
Hello,

I have created the branches. They are all currently pointing to the latest master.

Cheers

**Comment by kk6ho** [comment]
Thanks Irving.  I've submitted a PR for each layer.

**Comment by kk6ho** [comment]
For each branch I mean :-)

**Comment by ssfivy** [comment]
All merged, thank you.
Re: sstate-cache rebuilds, I don't have a persistent build setup just for CI of this layer or somewhere to store the cache, otherwise yes that would be ideal.
Out of curiosity, what are the advantages you found for using AWS builds vs having a dedicated on premise machines?

**Comment by kk6ho** [comment]
Thanks.

I'm not the guy who switched our CI over to AWS but here is what I see.

Pros:

   - Build machine is a Docker/Crops container that is well defined and the
   configuration is controlled by code.
   - Build machine is ephemeral, it disappears after the build is done and
   build assets are transferred somewhere else. So you are not charged by AWS
   to keep an instance in the cloud all the time.
   - You can use machines with a large number of cores to speed up Yocto
   builds.  I can't remember the sweet spot, but there is a point
   of diminishing returns on the number of cores vs. build time.
   - Capacity is elastic. We can spin up multiple instances and not slow
   down concurrent builds.
   - To save money, we use spot instances of machines rather than
   on-demand. So, we may have to wait occasionally for an EC2 instance or our
   instance may be terminated if AWS needs it. This rarely happens, but not a
   big deal since we can restart a build and have it start where it was
   interrupted.
   -

Cons:

   - Being ephemeral, if there is a problem with a build, you can't ssh to
   the machine to poke around to debug unless you setup a debug flag to keep
   the machine up after the build for a few hours.
   - There is some overhead on the order of minutes to wait for an EC2
   instance availability, download and spinup the container, and checkout the
   Yocto meta-layers (we may do some caching on that).
   - You'll need some clould storage to persistently store the download
   cache, containers, and the bulid assets.

In general the AWS solution has been more reliable and faster than our
on-prem.  That said, the on-premises server had some other things hindering
it.  It was a large server, but partitioned into a bunch of virtual
machines and network storage - not the ideal Yocto build machine. If I had
the same machine running  a bare-metal Linux OS with local SSD storage and
ram disks I could have made it run much faster.




Cons

**Pull request merged**
