### PR TITLE
added langdale to configuration file to allow for master to build

### PR DESCRIPTION
**Pull request by kk6ho**
Signed-off-by: Rodrigo Rengifo <rodrigo.rengifo@arthrex.com>

### CODE REVIEW

**Comment by kk6ho** [comment]
Would also like to create a new 'langdale' branch from this commit for Yocto 4.1

**Comment by kk6ho** [comment]
This is a dupe of @rarengifoArthrex 's PR. I modified the commit message slightly so the same commit could be used for the master branch and for the new langdale branch.

**Comment by ssfivy** [comment]
Thanks, just merged and branch created.

I'm not doing Yocto stuff anymore, so I wonder if it's better off if I gave you direct access or something along the line? That way you don't have to keep creating PRs and waiting for me to OK them.

**Comment by kk6ho** [comment]
Thanks for merging the changes.

At this point it seems like the changes to meta-noto will only be updates
to LAYERSERISE_COMPAT variable and making release branches, unless there is
some unexpected bitbake syntax change in the future. I could handle those
changes if you can grant me access to your repo. That's fine with me.

**Comment by ssfivy** [comment]
Ok, just added you as a collaborator. Let me know if you're still missing any accesses / permissions.

**Pull request merged**
